Merging 'tensorboard-integration' with 'master'
uavaustin/hawk-eye pull request #14
Opened 2020-10-30 18:55 UTC by kadhirumasankar

Added a function to `logger.py` which logs metrics (namely model score, the best model score, EMA score, the best EMA score, and training loss) to TensorBoard files inside `~/runs/uav-classifier/`

TensorBoard can be run using `tensorboard --logdir=~/runs/uav-classifier/`

2020-10-31 02:54 UTC, kadhirumasankar reviewed
👍

2020-10-31 02:54 UTC, kadhirumasankar commented on hawk_eye/configs/vovnet.yaml
> +  batch_size: 1
Need to change this back

2020-10-31 02:54 UTC, kadhirumasankar commented on hawk_eye/train/train_clf.py
> +
↪️

2020-10-31 06:47 UTC, alexwitt2399 approved these changes
Nice work to all involved! Small change requested withe imports, and can you add the loss to the log, too?

2020-10-31 06:47 UTC, alexwitt2399 commented on hawk_eye/train/train_utils/logger.py
> +import torch.utils.tensorboard as tensorboard
Leave empty line here:
```
system

external

project
```

2020-10-31 06:49 UTC, alexwitt2399 requested changes
Sorry, meant to request changes on the review above

2020-10-31 19:01 UTC, kadhirumasankar commented
> Nice work to all involved! Small change requested withe imports, and can you add the loss to the log, too?

@alexwitt2399 training loss is already being logged with `log.info` and `log.metric` (i.e. to TensorBoard). What do I need to change?

2020-11-01 00:51 UTC, alexwitt2399 commented
I see, I missed that line. LGTM

2020-11-01 00:51 UTC, alexwitt2399 approved these changes

2020-11-01 00:51 UTC, merged