merge tensorboard-integration-ap with tensorboard-integration-ku
uavaustin/hawk-eye pull request #7
Opened 2020-10-27 23:30 UTC by anyaprice

2020-10-29 23:37 UTC, kadhirumasankar commented on train/train_clf.py
> +from torchvision import datasets, transforms
We don't need these. You can delete them

2020-10-29 23:39 UTC, kadhirumasankar commented on train/train_clf.py
> +
You can delete these

2020-10-29 23:41 UTC, kadhirumasankar requested changes
Just need to delete a few lines and I'll merge your branch with mine

2020-10-29 23:57 UTC, kadhirumasankar approved these changes
Looks good to me 👍

2020-10-30 00:31 UTC, alexwitt2399 approved these changes
lgtm

2020-10-30 00:31 UTC, alexwitt2399 commented on train/train_utils/logger.py
> +        self.writer = SummaryWriter(log_dir=log_file.parent)
See style guide [here](https://google.github.io/styleguide/pyguide.html#22-imports) on importing modules.

2020-10-30 15:28 UTC, merged