Merge Tensorboard-intgration-bp with tensorboard-integration-ku
uavaustin/hawk-eye pull request #8
Opened 2020-10-27 23:30 UTC by bprimal22

2020-10-29 23:48 UTC, kadhirumasankar commented on .gitignore
> +runs
We don't need this line. You can delete it

2020-10-29 23:48 UTC, kadhirumasankar commented on README.md
> +    --config configs/vovnet.yaml
@alexwitt2399 keep this change?

2020-10-29 23:49 UTC, kadhirumasankar requested changes
Just fix .gitignore and we'll be good to merge

2020-10-29 23:50 UTC, alexwitt2399 commented on README.md
> +    --config configs/vovnet.yaml
yeah those changes are right

2020-10-30 00:00 UTC, kadhirumasankar approved these changes
Looks good to me 👍

2020-10-30 00:28 UTC, merged